// flow-typed signature: 79006a2a9b03805a37b7bd2bab2345ee
// flow-typed version: <<STUB>>/server-destroy_v^1.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'server-destroy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'server-destroy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'server-destroy/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'server-destroy/index' {
  declare module.exports: $Exports<'server-destroy'>;
}
declare module 'server-destroy/index.js' {
  declare module.exports: $Exports<'server-destroy'>;
}
declare module 'server-destroy/test.js' {
  declare module.exports: $Exports<'server-destroy/test'>;
}
