// flow-typed signature: d4176bbf37452b04e2a344ba3ff14a0d
// flow-typed version: <<STUB>>/travis-encrypt_v^2.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-encrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-encrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'travis-encrypt/bin/travis-encrypt-cli' {
  declare module.exports: any;
}

declare module 'travis-encrypt/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'travis-encrypt/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'travis-encrypt/lib/travis-encrypt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'travis-encrypt/bin/travis-encrypt-cli.js' {
  declare module.exports: $Exports<'travis-encrypt/bin/travis-encrypt-cli'>;
}
declare module 'travis-encrypt/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'travis-encrypt/coverage/lcov-report/prettify'>;
}
declare module 'travis-encrypt/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'travis-encrypt/coverage/lcov-report/sorter'>;
}
declare module 'travis-encrypt/lib/travis-encrypt.js' {
  declare module.exports: $Exports<'travis-encrypt/lib/travis-encrypt'>;
}
